### ISSUE TITLE
support jekyll 4.0.0

### ISSUE THREAD

**Issue by ashishdasnurkar** [thelehhman/plainwhite-jekyll#30]
Got following erro while trying to install for jekyll 

```
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll (~> 4.0.0)

    plainwhite was resolved to 0.5.0, which depends on
      jekyll (~> 3.8)
```

**Comment by thelehhman** [comment]
Its already supported, there was a versioning error.
Fixed in https://github.com/thelehhman/plainwhite-jekyll/commit/eb36cd6d6571023ee342657ee4ced037108a41bd.
rubygems by tommorow.

**Comment by redoine-zitouni** [comment]
I have the same error. I do not understand how to add your fixes. 
Would you like to explain it to us please ?
Many thanks,

**Comment by ashishdasnurkar** [comment]
Hey @thelehhman Thank you looking into it and fixing it. @redoine-zitouni the fix is not yet in rubygems I believe. Atleast that's what I see here https://rubygems.org/gems/plainwhite/versions/0.6 (Not a ruby dev so not sure if that is the right place to look)

**Comment by redoine-zitouni** [comment]
@ashishdasnurkar Yep, not a ruby dev too .. I have done a work-around. Just edit your Gemfile with : 
$ gem "jekyll", "~> 3.8" rather than $ gem "jekyll", "~> 4.0.0"
Then run : $ bundle update
As, according to my linux terminal : 
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by thelehhman** [comment]
Okay, you shouldn't face the issue now.
Pushed the new build(0.9) to rubygems: https://rubygems.org/gems/plainwhite/versions/0.9

**Comment by ashishdasnurkar** [comment]
Brilliant, works now. Thank you @thelehhman appreciate it.
