### ISSUE TITLE
Layout off on iOS

### ISSUE THREAD

**Issue by eklavya** [thelehhman/plainwhite-jekyll#57]
Hi, loving the design so far. Keep up the good work 👍 

Layout is not working on iPhone, works fine in android.

![IMG_6A2482F03F2A-1](https://user-images.githubusercontent.com/1136647/83332288-f1f06580-a2b7-11ea-93e7-87bedf05cdf2.jpeg)

Would also love to get proper categories and tags support but I don't want to burden you with stuff 😃

**Comment by thelehhman** [comment]
Oh. I believe that's an issue with Safari. Thanks for the heads up!

**Comment by DotIN13** [comment]
That's weird. When I test with my ipad, the problem showed up on `thelehhman.com` but not on my own site.

**Comment by DotIN13** [comment]
Okay, I think I still haven't fuly understand its mechanism, but I know now how to tackle that.

The problem was with the conbined effect of `html, body { height: 100%; }`, which I added to allow unfocusing the searchbar when the document body was clicked, and the browser default `main .about { flex-shrink: 1; }`. Looks like with the two styles together, safari is not giving flex item correct minimum height.

There are two workarounds that I have found to address this issue.

1. Add `main .about { flex-shrink: 0; }` to search.scss, which will prevent aggressive shrinkage of the about section.

2. Alternatively wrapping the `.about` section with a block display `<div>` would also solve this problem.
 
@thelehhman Since it's a single liner, I think you could just give it an easy fix!

**Comment by thelehhman** [comment]
@DotIN13 PR welcome :)

**Comment by DotIN13** [comment]
> @DotIN13 PR welcome :)
> Since you described the fix, you deserve the ownership.

Okey, I'll work on that.😀
